return {

	-- "mg979/vim-visual-multi",
	--
	-- init = function()
	--
	-- 	vim.g.VM_default_mappings = 0
	-- 	vim.g.VM_add_cursor_at_pos_no_mappings = 1
	-- 	vim.g.VM_set_statusline = 0
	-- 	-- vim.g.VM_notify_previously_selected = 2
	--
	-- 	vim.g.VM_maps = {
	-- 		["Find Under"] = "<C-n>",
	-- 		["Select All"] = "<leader>ma",
	-- 		["Start Regex Search"] = "<leader>mr",
	-- 		-- ["Add Cursor At Pos"] = "<leader>mp",
	-- 		-- ["Add Cursor Down"] = "<M-j>",
	-- 		-- ["Add Cursor Up"] = "<M-k>",
	-- 		-- ["Toggle Multiline"] = "<leader>mt",
	-- 		-- ["Toggle Mappings"] = "<leader>mo",
	-- 	}
	--
	-- 	-- local function visual_cursors_with_delay()
	-- 	-- 	vim.cmd('silent! execute "normal! \\<Plug>(VM-Visual-Cursors)"')
	-- 	-- 	vim.cmd('silent! execute "normal! A"')
	-- 	-- end
	-- 	--
	-- 	-- vim.keymap.set("v", "<leader>mv", visual_cursors_with_delay, { desc = "VM: visual cursors then append" })
	--
	-- 	-- Extra buffer maps after VM installs its own (see :help visual_multi_mappings).
	-- 	local group = vim.api.nvim_create_augroup("visual_multi_buffer_extras", { clear = true })
	-- 	local function feed_plug(keys)
	-- 		local t = vim.api.nvim_replace_termcodes(keys, true, false, true)
	-- 		vim.api.nvim_feedkeys(t, "m", false)
	-- 	end
	--
	-- 	local function vm_ctrl_c()
	-- 		local Vm = vim.g.Vm
	-- 		if type(Vm) == "table" and Vm.extend_mode == 1 then
	-- 			feed_plug("<Plug>(VM-Switch-Mode)")
	-- 		else
	-- 			feed_plug("<Plug>(VM-Exit)")
	-- 		end
	-- 	end
	--
	-- 	local function vm_sync_active_region()
	-- 		local sel = vim.b.VM_Selection
	-- 		if type(sel) ~= "table" or type(sel.Global) ~= "table" then
	-- 			return
	-- 		end
	-- 		pcall(vim.cmd, "call b:VM_Selection.Global.select_region_at_pos('.')")
	-- 	end
	--
	-- 	--- After VM find-under (especially the wrap-stop / `` path), cursor can match the
	-- 	--- screen while inline diagnostics still use a stale row; nudge cursor + CursorMoved.
	-- 	-- local function vm_refresh_cursor_state(buf)
	-- 	-- 	if vim.api.nvim_get_current_buf() ~= buf then
	-- 	-- 		return
	-- 	-- 	end
	-- 	-- 	local win = vim.api.nvim_get_current_win()
	-- 	-- 	local pos = vim.api.nvim_win_get_cursor(win)
	-- 	-- 	vim.api.nvim_win_set_cursor(win, pos)
	-- 	-- 	pcall(vim.api.nvim_exec_autocmds, "CursorMoved", { buffer = buf })
	-- 	-- end
	--
	-- 	vim.api.nvim_create_autocmd("User", {
	-- 		group = group,
	-- 		pattern = "visual_multi_mappings",
	-- 		callback = function()
	-- 			local buf = vim.api.nvim_get_current_buf()
	--
	-- 			vim.keymap.set("n", "<C-c>", vm_ctrl_c, {
	-- 				buffer = buf,
	-- 				nowait = true,
	-- 				silent = true,
	-- 				desc = "VM: switch mode or exit",
	-- 			})
	--
	-- 			-- Maps `v` to VM's Select Operator (like the default `s`): e.g. viw, vaw, vi".
	-- 			-- NOTE: intentionally loses raw `v` (charwise visual) while VM is active.
	-- 			vim.keymap.set("n", "v", "<Plug>(VM-Select-Operator)", {
	-- 				buffer = buf,
	-- 				remap = true,
	-- 				silent = true,
	-- 				desc = "VM: select operator",
	-- 			})
	--
	-- 			-- <C-n> calls VM's internal find-under, then re-syncs the active region by
	-- 			-- position. VM_notify_previously_selected=2 restores the cursor via `` but
	-- 			-- does not update s:v.index, so without the re-sync the wrong region stays
	-- 			-- active. The guard on b:VM_Selection prevents a call during early init.
	-- 			-- vim.keymap.set("n", "<C-n>", function()
	-- 			-- 	local buf = vim.api.nvim_get_current_buf()
	-- 			-- 	vim.fn["vm#commands#ctrln"](vim.v.count1)
	-- 			-- 	vim.schedule(function()
	-- 			-- 		vm_sync_active_region()
	-- 			-- 		vm_refresh_cursor_state(buf)
	-- 			-- 	end)
	-- 			-- end, {
	-- 			-- 	buffer = buf,
	-- 			-- 	silent = true,
	-- 			-- 	desc = "VM: find under + sync active region",
	-- 			-- })
	-- 		end,
	-- 	})
	--
	-- 	vim.api.nvim_create_autocmd("User", {
	-- 		group = group,
	-- 		pattern = "visual_multi_exit",
	-- 		callback = function()
	-- 			local buf = vim.api.nvim_get_current_buf()
	-- 			for _, lhs in ipairs({ "<C-c>", "v", "<C-n>" }) do
	-- 				pcall(vim.keymap.del, "n", lhs, { buffer = buf })
	-- 			end
	-- 		end,
	-- 	})
	-- end,
}
